name: Music
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+4

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^5.0.0
  cupertino_icons: ^0.1.3
  youtube_explode_dart: ^1.4.1
  path_provider:
  sqflite: 1.3.1
  flutter_local_notifications: 1.4.4+1
  equatable: ^1.2.0
  palette_generator: 0.2.3
  focused_menu: 1.0.1
  assets_audio_player: 2.0.6+5
  url_launcher: ^5.4.11
  cloud_firestore: 0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  flutter_launcher_icons: '^0.7.3'

flutter:
  assets:
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

  uses-material-design: true

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/icon.png'
  adaptive_icon_background: '#1a1947'
