name: music
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.3.0
  cupertino_icons: ^1.0.3
  youtube_explode_dart: ^1.10.7
  path_provider:
  sqflite: ^2.0.0
  flutter_local_notifications: ^8.2.0
  equatable: ^2.0.3
  focused_menu: ^1.0.5
  assets_audio_player: ^3.0.3
  url_launcher: ^6.0.12
  package_info: ^2.0.2
  image: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  assets:
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

  uses-material-design: true

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/icon.png'
  adaptive_icon_background: '#1a1947'
